model:
  _target_: tfmdoc.Tfmd
  d_model: 32
  d_demo: 2
  n_blocks: 2
  n_heads: 8
  max_len: 6000
  dropout: 0.5
  max_pool: True
  d_ff: 8
  transformer: True
  d_bow: 8
  lr: 0.001


preprocess:
  data_dir: "/nfs/turbo/lsa-regier/OPTUM2/"
  output_dir: "/nfs/turbo/lsa-regier/OPTUM2/preprocessed_files/"
  min_length: 8
  max_length: 512
  min_year: 2002
  max_year: 2018
  n: 600000
  include_labs: True
  do: False
  split_codes: True
  etl_only: False
  prediction_window: 30

train:
  train_frac: 0.75
  val_frac: 0.1
  gpus:
    - 6
  batch_size: 32
  max_epochs: 5
  limit_train_batches: 1.0
  save_prediction: False
  shuffle: False
  synth_labels: ""
  random_seed: 42

disease_codes:
  ald:
    - "5711"
    - "5712"
    - "5713"
    - "5715"
    - "K7010"
    - "K7011"
    - "K7041"
    - "K7030"
    - "K702"
    - "K700"
    - "K709"
    - "K7031"
    - "K7040"
    - "K7460"
    - "K7469"


# best checkpoints:
# transformer: outputs/2021-09-03/10-36-29/lightning_logs/version_0/checkpoints/epoch=9-step=38409.ckpt
# bow: ?
