transformer:
  _target_: tfmdoc.Transformer
  d_model: 64
  n_blocks: 2
  n_heads: 8
  max_len: 6000
  block_dropout: 0.5
  max_pool: True

preprocess:
  data_dir: "/nfs/turbo/lsa-regier/OPTUM2/"
  output_dir: "/nfs/turbo/lsa-regier/OPTUM2/preprocessed_files/"
  min_length: 32
  max_length: 512
  min_year: 2002
  max_year: 2018
  n: 600000
  include_labs: True
  do: False
  split_codes: True
  etl_only: False

train:
  train_frac: 0.8
  gpus:
    - 4
  batch_size: 32
  max_epochs: 5

disease_codes:
  ald:
    - "5711"
    - "5712"
    - "5713"
    - "5715"
    - "K7010"
    - "K7011"
    - "K7041"
    - "K7030"
    - "K702"
    - "K700"
    - "K709"
    - "K7031"
    - "K7040"
    - "K7460"
    - "K7469"
