bert: &bert
  _target_: tfmdoc.BERT
  d_model: 32
  n_blocks: 4
  n_heads: 8
  dropout: 0.1
  lr: 0.001


model:
  <<: *bert
  _target_: tfmdoc.Tfmd
  transformer: True
  d_ff: 32
  d_bow: []


pretrain: &pretrain
  train_frac: 0.85
  val_frac: 0.15
  gpus:
    - 6
  batch_size: 8
  max_epochs: 1
  limit_train_batches: 1.0
  random_seed: 42


train:
  <<: *pretrain
  train_frac: 0.75
  val_frac: 0.1
  batch_size: 64
  max_epochs: 5
  shuffle: False
  synth_labels: ""

mode: pretraining

preprocess:
  data_dir: "/nfs/turbo/lsa-regier/OPTUM2/"
  output_dir: "/nfs/turbo/lsa-regier/OPTUM2/preprocessed_files/"
  filename: "test_etl"
  min_length: 8
  max_length: 512
  min_year: 2002
  max_year: 2018
  n: 500000
  include_labs: True
  do: False
  split_codes: True
  prediction_window: 30
  disease: "NA"
  mode: "pretraining"
  early_detection: 0


disease_codes:
  ald:
    - "5711"
    - "5712"
    - "5713"
    - "5715"
    - "K7010"
    - "K7011"
    - "K7041"
    - "K7030"
    - "K702"
    - "K700"
    - "K709"
    - "K7031"
    - "K7040"
    - "K7460"
    - "K7469"
  bleed:
    - "K922"
    - "5789"
  thinner:
    - "WARFARIN SODIUM"
    - "COUMADIN"

pad:
  ald: 7
  bleed: 7
  thinner: 30


# best checkpoints:
# transformer: outputs/2021-09-03/10-36-29/lightning_logs/version_0/checkpoints/epoch=9-step=38409.ckpt
# bow: ?

hydra:
  sweep:
    dir: multirun/${preprocess.mode}/${preprocess.filename}/${now:%Y-%m-%d}/${now:%H-%M-%S}
