# This workflow will install Python dependencies, run tests.
# For more information see:
# https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        python-version: [3.8]

    steps:

    - name: Checkout github repo (+ download lfs dependencies)
      uses: actions/checkout@v2
      with:
        lfs: false

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry
      run: |
        pip install --upgrade pip
        pip install "poetry >=1.1.4, <2.0.0"

    - name: Install dependencies
      run: |
        poetry install

    - name: Run pylint
      run: |
        poetry run pylint ehr/ tests/

    # - name: Run flake8
    #   run: |
    #     poetry run flake8 ehr/ tests/

    - name: Run black
      run: |
        poetry run black --check ehr/ tests/

    - name: Run Tests
      run: |
        poetry run pytest --cov=./ehr --cov-report=xml --durations=0

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        file: ./coverage.xml
        flags: unittests
        env_vars: OS,PYTHON
        name: codecov-umbrella
        fail_ci_if_error: true
